/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teproductos.visual;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import teproductos.model.Categoria;
import teproductos.model.Data;
import teproductos.model.Marca;
import teproductos.model.Producto;
import teproductos.tmproductos.TMProductos;
import teproductos.visual.renderer.Renderer;
/**
 *
 * @author igor
 */
public class Ventana extends javax.swing.JFrame {
    private Data data;
    private boolean esTodoCargado = false;
    public Ventana() {
        try {
            initComponents();
            data = new Data();
            centrarVentana();
            cargarCombos();            
            refrescar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLError",
                ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "IOError",
               "Some problems during reading config file:" + ex.getMessage(), 
                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void centrarVentana(){
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        pnlProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkBoxTransReg = new javax.swing.JCheckBox();
        checkBoxDisponibleReg = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        comboCategoriaReg = new javax.swing.JComboBox();
        comboMarcaReg = new javax.swing.JComboBox();
        spinnerPrecioReg = new javax.swing.JSpinner();
        txtFechaReg = new javax.swing.JTextField();
        pnlTrans = new javax.swing.JPanel();
        pnlBuscar = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spinnerPrecioMIN = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spinnerPrecioMAX = new javax.swing.JSpinner();
        comboCategoriaBuscar = new javax.swing.JComboBox();
        checkBoxNoTrans = new javax.swing.JCheckBox();
        checkBoxSoloDisponible = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        comboCriterioBuscar = new javax.swing.JComboBox<>();
        rbtnAumento = new javax.swing.JRadioButton();
        rbtnDescenso = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFechaMIN = new javax.swing.JTextField();
        txtFechaMAX = new javax.swing.JTextField();
        btnReseteo = new javax.swing.JButton();
        checkBoxPrecio = new javax.swing.JCheckBox();
        checkBoxCategoriaBuscar = new javax.swing.JCheckBox();
        checkBoxMarcaBuscar = new javax.swing.JCheckBox();
        checkBoxFechaBuscar = new javax.swing.JCheckBox();
        comboMarcaBuscar = new javax.swing.JComboBox();
        btnCargarListadoCompleto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeProductos");

        tabla.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        pnlProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Categoria:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fecha:");

        checkBoxTransReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBoxTransReg.setText("Transgenico");

        checkBoxDisponibleReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBoxDisponibleReg.setSelected(true);
        checkBoxDisponibleReg.setText("Disponible");

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setText("xxxx");

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        comboCategoriaReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboCategoriaReg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboMarcaReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboMarcaReg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spinnerPrecioReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinnerPrecioReg.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(1.0E12f), Float.valueOf(1.0f)));
        spinnerPrecioReg.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerPrecioReg, "#,##0.###"));

        txtFechaReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        pnlTrans.setBackground(new java.awt.Color(255, 255, 255));
        pnlTrans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlTransLayout = new javax.swing.GroupLayout(pnlTrans);
        pnlTrans.setLayout(pnlTransLayout);
        pnlTransLayout.setHorizontalGroup(
            pnlTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTransLayout.setVerticalGroup(
            pnlTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlProductoLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(70, 70, 70))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductoLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(pnlProductoLayout.createSequentialGroup()
                                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblID)
                                    .addComponent(comboCategoriaReg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMarcaReg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerPrecioReg)
                                    .addComponent(txtFechaReg)
                                    .addComponent(txtNombre)))
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(checkBoxTransReg)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxDisponibleReg)))
                .addContainerGap())
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategoriaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMarcaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerPrecioReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(checkBoxTransReg))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxDisponibleReg)
                            .addComponent(pnlTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar productos por la base de datos"));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel10.setText("MIN");

        spinnerPrecioMIN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinnerPrecioMIN.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(1.0E12f), Float.valueOf(1.0f)));
        spinnerPrecioMIN.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerPrecioMIN, ""));
        spinnerPrecioMIN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPrecioMINStateChanged(evt);
            }
        });

        jLabel11.setText("MAX");

        spinnerPrecioMAX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spinnerPrecioMAX.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(1.0E12f), Float.valueOf(1.0f)));
        spinnerPrecioMAX.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerPrecioMAX, ""));
        spinnerPrecioMAX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPrecioMAXStateChanged(evt);
            }
        });

        comboCategoriaBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboCategoriaBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        comboCategoriaBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCategoriaBuscarItemStateChanged(evt);
            }
        });
        comboCategoriaBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboCategoriaBuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboCategoriaBuscarMouseReleased(evt);
            }
        });
        comboCategoriaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaBuscarActionPerformed(evt);
            }
        });

        checkBoxNoTrans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBoxNoTrans.setText("Sólo no transgenicos");
        checkBoxNoTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNoTransActionPerformed(evt);
            }
        });

        checkBoxSoloDisponible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBoxSoloDisponible.setText("Sólo disponibles");
        checkBoxSoloDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSoloDisponibleActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ordenar por");

        comboCriterioBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboCriterioBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Categoria", "Marca", "Precio", "Fecha" }));
        comboCriterioBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCriterioBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnAumento);
        rbtnAumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnAumento.setSelected(true);
        rbtnAumento.setText("aumento");
        rbtnAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAumentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnDescenso);
        rbtnDescenso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnDescenso.setText("descenso");
        rbtnDescenso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDescensoActionPerformed(evt);
            }
        });

        jLabel14.setText("MIN");

        jLabel15.setText("MAX");

        txtFechaMIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFechaMAX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnReseteo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReseteo.setText("Reseteo");
        btnReseteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReseteoActionPerformed(evt);
            }
        });

        checkBoxPrecio.setText("Considerar el precio");
        checkBoxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPrecioActionPerformed(evt);
            }
        });

        checkBoxCategoriaBuscar.setText("Considerar sólo la categoria de");
        checkBoxCategoriaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCategoriaBuscarActionPerformed(evt);
            }
        });

        checkBoxMarcaBuscar.setText("Considerar sólo la marca de");
        checkBoxMarcaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMarcaBuscarActionPerformed(evt);
            }
        });

        checkBoxFechaBuscar.setText("Considerar fecha");
        checkBoxFechaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFechaBuscarActionPerformed(evt);
            }
        });

        comboMarcaBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboMarcaBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMarcaBuscarItemStateChanged(evt);
            }
        });
        comboMarcaBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboMarcaBuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboMarcaBuscarMouseReleased(evt);
            }
        });
        comboMarcaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarcaBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCriterioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkBoxNoTrans))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxSoloDisponible)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addComponent(rbtnAumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnDescenso)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxMarcaBuscar)
                                    .addComponent(checkBoxCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCategoriaBuscar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMarcaBuscar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarLayout.createSequentialGroup()
                                .addComponent(checkBoxFechaBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaMAX, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addComponent(checkBoxPrecio)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(spinnerPrecioMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerPrecioMAX, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBuscarLayout.createSequentialGroup()
                                .addComponent(txtBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReseteo)))
                        .addGap(7, 7, 7))))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnReseteo))
                .addGap(18, 18, 18)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spinnerPrecioMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(spinnerPrecioMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxCategoriaBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxMarcaBuscar)
                    .addComponent(comboMarcaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlBuscarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(checkBoxFechaBuscar)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBuscarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxNoTrans)
                    .addComponent(checkBoxSoloDisponible))
                .addGap(8, 8, 8)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCriterioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(rbtnAumento)
                    .addComponent(rbtnDescenso))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnCargarListadoCompleto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCargarListadoCompleto.setText("Cargar listado completo");
        btnCargarListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarListadoCompletoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar selección");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnQuitar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuitar.setText("Quitar aplicación");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCargarListadoCompleto)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarListadoCompleto)
                    .addComponent(btnCancelar)
                    .addComponent(btnQuitar))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTabla() throws SQLException{
        ArrayList<Producto> productos = data.getListaProducto();
        TMProductos tmodel = new TMProductos(productos, data);
        Renderer renderer = new Renderer();
        tabla.setModel(tmodel);
        tabla.setDefaultRenderer(Object.class, renderer);
    }
    
    private void cargarCombos() throws SQLException{
        ArrayList<Categoria> categorias = data.getListaCategoria();
        comboCategoriaReg.removeAllItems();
        comboCategoriaBuscar.removeAllItems();
        for(Categoria c : categorias){
            comboCategoriaReg.addItem(c);
            comboCategoriaBuscar.addItem(c);
        }
        comboMarcaBuscar.removeAllItems();
        comboMarcaReg.removeAllItems();
        ArrayList<Marca> marcas = data.getListaMarca();
        for(Marca m : marcas){
            comboMarcaBuscar.addItem(m);
            comboMarcaReg.addItem(m);
        }
        esTodoCargado = true;
    }
    
    private void limpiarVormulario(){
        lblID.setText("xxxxx");
        txtNombre.setText(null);
        comboCategoriaBuscar.setSelectedIndex(0);
        comboMarcaReg.setSelectedIndex(0);
        spinnerPrecioReg.setValue(0.0f);
        txtFechaReg.setText(null);        
        checkBoxTransReg.setSelected(false);
        checkBoxDisponibleReg.setSelected(false);
        pnlTrans.setBackground(Color.WHITE);
    }
    
    private void refrescar() throws SQLException{
        cargarTabla();
        limpiarVormulario();
        txtNombre.requestFocus();
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    private Producto rescatarDatos(boolean mayBeRegisterExists){
        Producto p = new Producto();
        String nombre = txtNombre.getText();
        p.setNombre(nombre.isEmpty() ? "Producto" : nombre);
        Categoria categoria = (Categoria)comboCategoriaReg.getSelectedItem();
        p.setCategoria(categoria.getId());
        Marca marca = (Marca)comboMarcaReg.getSelectedItem();
        p.setMarca(marca.getId());
        p.setPrecio((float)spinnerPrecioReg.getValue());
        p.setFecha(txtFechaReg.getText());
        p.setTransgenic(checkBoxTransReg.isSelected());
        p.setDisponible(checkBoxDisponibleReg.isSelected());
        if(mayBeRegisterExists){
            p.setId(Integer.parseInt(lblID.getText()));
        }
        return p;
    }    
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            data.meterProducto(rescatarDatos(false));
            refrescar();
            JOptionPane.showMessageDialog(null, "El producto fué registrado con éxito.",
                "DataBase Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "DataBase Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            data.modificarProducto(rescatarDatos(true));
            refrescar();
            JOptionPane.showMessageDialog(null, "El producto fué modifcado con éxito.",
                "DataBase Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "DataBase Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            data.eliminarProducto(Integer.parseInt(lblID.getText()));
            refrescar();
            JOptionPane.showMessageDialog(null, "El producto fué eliminado con éxito.",
                "DataBase Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "DataBase Error",
                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (esTodoCargado) {
            try {
                String regExp = txtBuscar.getText();
                boolean precio = checkBoxPrecio.isSelected();
                boolean soloUnaCategoria = checkBoxCategoriaBuscar.isSelected();
                System.out.println(comboCategoriaBuscar.getItemCount());
                int id_categoria = ((Categoria) comboCategoriaBuscar.getSelectedItem()).getId();
                boolean soloUnaMarca = checkBoxMarcaBuscar.isSelected();
                System.out.println(comboMarcaBuscar.getItemCount());
                //int id_marca = comboMarcaBuscar.getSelectedIndex() + 1;
                int id_marca = ((Marca) comboMarcaBuscar.getSelectedItem()).getId();
                float precioMin = (float) spinnerPrecioMIN.getValue();
                float precioMax = (float) spinnerPrecioMAX.getValue();
                boolean fecha = checkBoxFechaBuscar.isSelected();
                String fechaMin = txtFechaMIN.getText();
                String fechaMax = txtFechaMAX.getText();
                boolean noTrans = checkBoxNoTrans.isSelected();
                boolean soloDisponibles = checkBoxSoloDisponible.isSelected();
                int orden_criterio = comboCriterioBuscar.getSelectedIndex();
                boolean ordenDescenso = rbtnDescenso.isSelected();
                ArrayList<Producto> productos = data.buscarProductos(regExp,
                        soloUnaCategoria, id_categoria, soloUnaMarca, id_marca, precio,
                        precioMin, precioMax, fecha, fechaMin, fechaMax, noTrans,
                        soloDisponibles, orden_criterio, ordenDescenso);
                TMProductos tmodel = new TMProductos(productos, data);
                tabla.setModel(tmodel);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "DataBase Error",
                        JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCargarListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarListadoCompletoActionPerformed
        try {
            cargarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "DataBase Error",
                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCargarListadoCompletoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            refrescar();
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased
        if(evt.getClickCount() == 1){
            int fila = tabla.getSelectedRow();
            TMProductos tmodel = (TMProductos)tabla.getModel();
            Producto p = tmodel.getProducto(fila);
            lblID.setText(String.valueOf(p.getId()));
            txtNombre.setText(p.getNombre());
            comboCategoriaReg.setSelectedItem(comboCategoriaReg.getItemAt(p.getCategoria() - 1));
            comboMarcaReg.setSelectedItem(comboMarcaReg.getItemAt(p.getMarca() - 1));
            spinnerPrecioReg.setValue(p.getPrecio());
            txtFechaReg.setText(p.getFecha());
            checkBoxTransReg.setSelected(p.isTransgenic());
            pnlTrans.setBackground(p.isTransgenic() ? Color.RED : Color.GREEN);
            checkBoxDisponibleReg.setSelected(p.isDisponible());
            btnRegistrar.setEnabled(false);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_tablaMouseReleased

    private void btnReseteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReseteoActionPerformed
        try {
            cargarTabla();
            txtBuscar.setText(null);
            checkBoxPrecio.setSelected(false);
            spinnerPrecioMIN.setValue(0.0f);
            spinnerPrecioMAX.setValue(0.0f);
            checkBoxCategoriaBuscar.setSelected(false);
            comboCategoriaBuscar.setSelectedIndex(0);
            checkBoxMarcaBuscar.setSelected(false);
            comboMarcaBuscar.setSelectedIndex(0);
            checkBoxFechaBuscar.setSelected(false);
            txtFechaMIN.setText(null);
            txtFechaMAX.setText(null);
            checkBoxNoTrans.setSelected(false);
            checkBoxSoloDisponible.setSelected(false);
            comboCriterioBuscar.setSelectedIndex(0);
            rbtnDescenso.setSelected(false);
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReseteoActionPerformed

    private void checkBoxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPrecioActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_checkBoxPrecioActionPerformed

    private void checkBoxCategoriaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCategoriaBuscarActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_checkBoxCategoriaBuscarActionPerformed

    private void checkBoxMarcaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMarcaBuscarActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_checkBoxMarcaBuscarActionPerformed

    private void checkBoxFechaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFechaBuscarActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_checkBoxFechaBuscarActionPerformed

    private void checkBoxNoTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNoTransActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_checkBoxNoTransActionPerformed

    private void checkBoxSoloDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSoloDisponibleActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_checkBoxSoloDisponibleActionPerformed

    private void comboCriterioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCriterioBuscarActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_comboCriterioBuscarActionPerformed

    private void rbtnAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAumentoActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_rbtnAumentoActionPerformed

    private void rbtnDescensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDescensoActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_rbtnDescensoActionPerformed

    private void comboCategoriaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaBuscarActionPerformed
        
        //btnBuscar.doClick();
    }//GEN-LAST:event_comboCategoriaBuscarActionPerformed

    private void spinnerPrecioMINStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPrecioMINStateChanged
        btnBuscar.doClick();
    }//GEN-LAST:event_spinnerPrecioMINStateChanged

    private void spinnerPrecioMAXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPrecioMAXStateChanged
        btnBuscar.doClick();
    }//GEN-LAST:event_spinnerPrecioMAXStateChanged

    private void comboCategoriaBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCategoriaBuscarItemStateChanged
        //btnBuscar.doClick();           
        if(comboCategoriaBuscar.getItemCount() > 0){
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_comboCategoriaBuscarItemStateChanged

    private void comboCategoriaBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCategoriaBuscarMouseReleased
        //btnBuscar.doClick();
    }//GEN-LAST:event_comboCategoriaBuscarMouseReleased

    private void comboCategoriaBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCategoriaBuscarMousePressed
        //btnBuscar.doClick();
    }//GEN-LAST:event_comboCategoriaBuscarMousePressed

    private void comboMarcaBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMarcaBuscarItemStateChanged
        // TODO add your handling code here:
        if(comboMarcaBuscar.getItemCount() > 0){
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_comboMarcaBuscarItemStateChanged

    private void comboMarcaBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMarcaBuscarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcaBuscarMousePressed

    private void comboMarcaBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMarcaBuscarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcaBuscarMouseReleased

    private void comboMarcaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcaBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarListadoCompleto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReseteo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxCategoriaBuscar;
    private javax.swing.JCheckBox checkBoxDisponibleReg;
    private javax.swing.JCheckBox checkBoxFechaBuscar;
    private javax.swing.JCheckBox checkBoxMarcaBuscar;
    private javax.swing.JCheckBox checkBoxNoTrans;
    private javax.swing.JCheckBox checkBoxPrecio;
    private javax.swing.JCheckBox checkBoxSoloDisponible;
    private javax.swing.JCheckBox checkBoxTransReg;
    private javax.swing.JComboBox comboCategoriaBuscar;
    private javax.swing.JComboBox comboCategoriaReg;
    private javax.swing.JComboBox<String> comboCriterioBuscar;
    private javax.swing.JComboBox comboMarcaBuscar;
    private javax.swing.JComboBox comboMarcaReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JPanel pnlTrans;
    private javax.swing.JRadioButton rbtnAumento;
    private javax.swing.JRadioButton rbtnDescenso;
    private javax.swing.JSpinner spinnerPrecioMAX;
    private javax.swing.JSpinner spinnerPrecioMIN;
    private javax.swing.JSpinner spinnerPrecioReg;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFechaMAX;
    private javax.swing.JTextField txtFechaMIN;
    private javax.swing.JTextField txtFechaReg;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
